# Use official Node.js LTS image
FROM node:20-alpine

# Set working directory inside container
WORKDIR /big-jumps-4-tods-frontend

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --frozen-lockfile

# Copy the rest of the frontend files
COPY . .

# Expose port 3000
EXPOSE 3000

# Start frontend app
CMD ["npm", "start"]
